### PR TITLE
Added 1080p mod without breaking AO with 2x resolution

### PR DESCRIPTION
**Pull request by 89pleasure**
I tested this mod in relation to other 1080p mods also the alternative 720p option and could not find any issues with AO so far. Picture does look very crisp. Never experienced a crash or anything weird since using this for 2 days now.

[https://imgsli.com/MTc5Nzc0/2/3](https://imgsli.com/MTc5Nzc0/2/3)

Im using yuzu EA 3599, Vulkan backend, AMD Radeon 5700X, 2x resolution.

I found it randomly while testing mods and don't know who is the origin. So I don't know who is to credit here.

### CODE REVIEW

**Comment by 89pleasure** [comment]
I also added a test with vanilla 1x resoltution for better comparison

**Comment by ajhix36** [comment]
If you look at the left side of the comparison by the gate, you will see that the lighting is much different than the 1x 1080p or vanilla. If you capture a comparison in a shrine , you will more easily see there are lighting changes that unfortunately indicate that 2x or higher scaling is not suitable for 1080p with the current mods that we have.

**Comment by 89pleasure** [comment]
Yes, I can see the difference too. However, in my opinion it is minimal. And as far as I can see, there is no problem with AO. You could even say the shadow is more "natural". But that may be a matter of taste. 

What would be the requirement for the mods? It wouldn't be the first mod that doesn't implement 100% of what is desired. 

Wouldn't the mod still make sense in the list? Let's let the user decide whether he wants to use it or not.

What do you think?

**Comment by Foul-Tarnished** [comment]
Do you have a version of it for 1.1.1 ?

**Comment by HolographicWings** [comment]
> I tested this mod in relation to other 1080p mods also the alternative 720p option and could not find any issues with AO so far. Picture does look very crisp. Never experienced a crash or anything weird since using this for 2 days now.
> 
> https://imgsli.com/MTc5Nzc0/2/3
> 
> Im using yuzu EA 3599, Vulkan backend, AMD Radeon 5700X, 2x resolution.
> 
> I found it randomly while testing mods and don't know who is the origin. So I don't know who is to credit here.

Could you made an img sli in the entrance of a shrine please ? It's hard to see AO outside
Like that : https://imgsli.com/MTc5MTI4/11/9

**Review by HolographicWings — CHANGES_REQUESTED** [review]
Could you made an img sli in the entrance of a shrine please ? It's hard to see AO outside
Like that : https://imgsli.com/MTc5MTI4/11/9

**Comment by 89pleasure** [comment]
Author of mod found and don't want to have this mod here shared with others.

**Comment by HolographicWings** [comment]
Okay

**Pull request closed without merging**
